In [13]:
class Employee:
    def __init__(self, name, number, address, salary, post, year_of_joining, education, year_of_experience):
        self.name = name
        self.number = number
        self.address = address
        self.salary = salary
        self.post = post
        self.year_of_joining = year_of_joining
        self.education = education
        self.year_of_experience = year_of_experience

    def describe_employee(self):
        print(f"Name: {self.name}\nNumber: {self.number}\nAddress: {self.address}\nSalary: {self.salary}\nPost: {self.post}\nYear of Joining: {self.year_of_joining}\nEducation: {self.education}\nYears of Experience: {self.year_of_experience}\n")

    def update_year_of_experience(self):
        self.year_of_experience += 1

    def increase_salary(self, amount):
        self.salary += amount


# Creating an instance employee101
employee101 = Employee("Muhammad osama", "101", "123 Main St", 50000, "Software Developer", 2015, "Bachelor's in CS", 8)

# Print four attributes individually
print(employee101.name)
print(employee101.number)
print(employee101.address)
print(employee101.salary)

# Call methods
employee101.describe_employee()
employee101.increase_salary(5000)
employee101.update_year_of_experience()

# Print updated details
print("\nAfter Updates:")
employee101.describe_employee()

# Creating 10 instances and calling describe_employee()
employees = [
    Employee("Haris afzal", "102", "gulshan town 13d", 60000, "Data Analyst", 2018, "Master's in Data Science", 5),
    Employee("yaqoob khan", "103", "Malir cant karachi", 55000, "Data Scientist", 2016, "Bachelor's in Statistics", 7),
    Employee("shehbaz hussain", "104", "Defence housing street.22", 70000, "AI Engineer", 2019, "Master's in AI", 4),
    Employee("zeeshan ahmed", "105", "gulistan-e-johar block 2", 65000, "ML Engineer", 2017, "PhD in Machine Learning", 6),
    Employee("daniyal nagori", "106", "Bahria town Islamabad", 48000, "Web Developer", 2020, "Bachelor's in IT", 3),
    Employee("kamran khan", "107", "punjab housing society", 72000, "Cloud Engineer", 2015, "Master's in Cloud Computing", 9),
    Employee("faisal siddiqui", "108", "scheme 33 gulistan-e-johar", 54000, "Backend Developer", 2016, "Bachelor's in Software Engineering", 6),
    Employee("farrukh haider", "109", "malir town city", 58000, "Frontend Developer", 2018, "Master's in Web Development", 5),
    Employee("saeed ahmed", "110", "model colony street.12", 50000, "Network Engineer", 2021, "Bachelor's in Network Security", 2),
    Employee("nasir buledi", "111", "pak society P.H.A", 76000, "DevOps Engineer", 2014, "Master's in DevOps", 10)
]

# Describe each employee
for emp in employees:
    emp.describe_employee()

# Apply some updates on specific employees
employees[0].increase_salary(2000)
employees[1].update_year_of_experience()
employees[2].increase_salary(1500)

Muhammad osama
101
johar town 225
50000
Name: Muhammad osama
Number: 101
Address: johar town 225
Salary: 50000
Post: Software Developer
Year of Joining: 2015
Education: Bachelor's in CS
Years of Experience: 8


After Updates:
Name: Muhammad osama
Number: 101
Address: johar town 225
Salary: 55000
Post: Software Developer
Year of Joining: 2015
Education: Bachelor's in CS
Years of Experience: 9

Name: Haris afzal
Number: 102
Address: gulshan town 13d
Salary: 60000
Post: Data Analyst
Year of Joining: 2018
Education: Master's in Data Science
Years of Experience: 5

Name: yaqoob khan
Number: 103
Address: Malir cant karachi
Salary: 55000
Post: Data Scientist
Year of Joining: 2016
Education: Bachelor's in Statistics
Years of Experience: 7

Name: shehbaz hussain
Number: 104
Address: Defence housing street.22
Salary: 70000
Post: AI Engineer
Year of Joining: 2019
Education: Master's in AI
Years of Experience: 4

Name: zeeshan ahmed
Number: 105
Address: gulistan-e-johar block 2
Salary: 65000
Post: ML Engineer
Year of Joining: 2017
Education: PhD in Machine Learning
Years of Experience: 6

Name: daniyal nagori
Number: 106
Address: Bahria town Islamabad
Salary: 48000
Post: Web Developer
Year of Joining: 2020
Education: Bachelor's in IT
Years of Experience: 3

Name: kamran khan
Number: 107
Address: punjab housing society
Salary: 72000
Post: Cloud Engineer
Year of Joining: 2015
Education: Master's in Cloud Computing
Years of Experience: 9

Name: faisal siddiqui
Number: 108
Address: scheme 33 gulistan-e-johar
Salary: 54000
Post: Backend Developer
Year of Joining: 2016
Education: Bachelor's in Software Engineering
Years of Experience: 6

Name: farrukh haider
Number: 109
Address: malir town city
Salary: 58000
Post: Frontend Developer
Year of Joining: 2018
Education: Master's in Web Development
Years of Experience: 5

Name: saeed ahmed
Number: 110
Address: model colony street.12
Salary: 50000
Post: Network Engineer
Year of Joining: 2021
Education: Bachelor's in Network Security
Years of Experience: 2

Name: nasir buledi
Number: 111
Address: pak society P.H.A
Salary: 76000
Post: DevOps Engineer
Year of Joining: 2014
Education: Master's in DevOps
Years of Experience: 10

# without using classes or OOP:

In [14]:
def create_employee(name, number, address, salary, post, year_of_joining, education, year_of_experience):
    return {
        "name": name,
        "number": number,
        "address": address,
        "salary": salary,
        "post": post,
        "year_of_joining": year_of_joining,
        "education": education,
        "year_of_experience": year_of_experience
    }

def describe_employee(employee):
    print(f"Name: {employee['name']}\nNumber: {employee['number']}\nAddress: {employee['address']}\nSalary: {employee['salary']}\nPost: {employee['post']}\nYear of Joining: {employee['year_of_joining']}\nEducation: {employee['education']}\nYears of Experience: {employee['year_of_experience']}\n")

def update_year_of_experience(employee):
    employee["year_of_experience"] += 1

def increase_salary(employee, amount):
    employee["salary"] += amount


# Creating an employee dictionary
employee101 = create_employee("Muhammad osama", "101", "johar town 225", 50000, "Software Developer", 2015, "Bachelor's in CS", 8)

# Print four attributes individually
print(employee101['name'])
print(employee101['number'])
print(employee101['address'])
print(employee101['salary'])

# Call functions
describe_employee(employee101)
increase_salary(employee101, 5000)
update_year_of_experience(employee101)

# Print updated details
print("\nAfter Updates:")
describe_employee(employee101)

# Creating 10 employees and calling describe_employee()
employees = [
    create_employee("Haris afzal", "102", "gulshan town 13d", 60000, "Data Analyst", 2018, "Master's in Data Science", 5),
    create_employee("yaqoob khan", "103", "Malir cant karachi", 55000, "Data Scientist", 2016, "Bachelor's in Statistics", 7),
    create_employee("shehbaz hussain", "104", "Defence housing street.22", 70000, "AI Engineer", 2019, "Master's in AI", 4),
    create_employee("zeeshan ahmed", "105", "gulistan-e-johar block 2", 65000, "ML Engineer", 2017, "PhD in Machine Learning", 6),
    create_employee("daniyal nagori", "106", "Bahria town Islamabad", 48000, "Web Developer", 2020, "Bachelor's in IT", 3),
    create_employee("kamran khan", "107", "punjab housing society", 72000, "Cloud Engineer", 2015, "Master's in Cloud Computing", 9),
    create_employee("faisal siddiqui", "108", "scheme 33 gulistan-e-johar", 54000, "Backend Developer", 2016, "Bachelor's in Software Engineering", 6),
    create_employee("farrukh haider", "109", "malir town city", 58000, "Frontend Developer", 2018, "Master's in Web Development", 5),
    create_employee("saeed ahmed", "110", "model colony street.12", 50000, "Network Engineer", 2021, "Bachelor's in Network Security", 2),
    create_employee("nasir buledi", "111", "pak society P.H.A", 76000, "DevOps Engineer", 2014, "Master's in DevOps", 10)
]

# Describe each employee
for emp in employees:
    describe_employee(emp)

# Apply some updates on specific employees
increase_salary(employees[0], 2000)
update_year_of_experience(employees[1])
increase_salary(employees[2], 1500)

Muhammad osama
101
johar town 225
50000
Name: Muhammad osama
Number: 101
Address: johar town 225
Salary: 50000
Post: Software Developer
Year of Joining: 2015
Education: Bachelor's in CS
Years of Experience: 8


After Updates:
Name: Muhammad osama
Number: 101
Address: johar town 225
Salary: 55000
Post: Software Developer
Year of Joining: 2015
Education: Bachelor's in CS
Years of Experience: 9

Name: Haris afzal
Number: 102
Address: gulshan town 13d
Salary: 60000
Post: Data Analyst
Year of Joining: 2018
Education: Master's in Data Science
Years of Experience: 5

Name: yaqoob khan
Number: 103
Address: Malir cant karachi
Salary: 55000
Post: Data Scientist
Year of Joining: 2016
Education: Bachelor's in Statistics
Years of Experience: 7

Name: shehbaz hussain
Number: 104
Address: Defence housing street.22
Salary: 70000
Post: AI Engineer
Year of Joining: 2019
Education: Master's in AI
Years of Experience: 4

Name: zeeshan ahmed
Number: 105
Address: gulistan-e-johar block 2
Salary: 65000
Post: ML Engineer
Year of Joining: 2017
Education: PhD in Machine Learning
Years of Experience: 6

Name: daniyal nagori
Number: 106
Address: Bahria town Islamabad
Salary: 48000
Post: Web Developer
Year of Joining: 2020
Education: Bachelor's in IT
Years of Experience: 3

Name: kamran khan
Number: 107
Address: punjab housing society
Salary: 72000
Post: Cloud Engineer
Year of Joining: 2015
Education: Master's in Cloud Computing
Years of Experience: 9

Name: faisal siddiqui
Number: 108
Address: scheme 33 gulistan-e-johar
Salary: 54000
Post: Backend Developer
Year of Joining: 2016
Education: Bachelor's in Software Engineering
Years of Experience: 6

Name: farrukh haider
Number: 109
Address: malir town city
Salary: 58000
Post: Frontend Developer
Year of Joining: 2018
Education: Master's in Web Development
Years of Experience: 5

Name: saeed ahmed
Number: 110
Address: model colony street.12
Salary: 50000
Post: Network Engineer
Year of Joining: 2021
Education: Bachelor's in Network Security
Years of Experience: 2

Name: nasir buledi
Number: 111
Address: pak society P.H.A
Salary: 76000
Post: DevOps Engineer
Year of Joining: 2014
Education: Master's in DevOps
Years of Experience: 10